### ISSUE TITLE
Erro ao executar todos os testes de uma vez

### ISSUE THREAD

**Issue by cesarviana** [Eitz/Mula#2]
I need help. The tests are failing when I execute they all in one time. But why?? 
One by one they are passing...
![screenshot - 18-05-2016 - 11 27 00](https://cloud.githubusercontent.com/assets/6049357/15362431/78e01cf4-1ceb-11e6-8ffb-81eea06a3dbd.png)

**Comment by CassianoViana** [comment]
Me declaro incompetente para resolver este problema :(
Não consegui identificar porque em
`mula.execute(
// @formatter:off
            "var <- 'var.txt';"+ // var.txt = 37
            "var2 = 4; "+
            "c = 50; " +
            "c = run 'java', <%" +
            "   System.out.println( %=c ); " +
            "   int soma = %=var + %=var2; " +
                        "   System.out.println(soma); " +        
            "   return soma; " +
            " %>;"
            );
// @formatter:on
        assertEquals(41, valorDe("c"));`
Retorna NullPointerException na chamada `valorDe("c")`

**Comment by cesarviana** [comment]
Haha @CassianoViana 
Falha minha. Agora está tudo ok.
